spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/todo_db
    username: todo_user
    password: secret
  jpa:
    hibernate:
      ddl-auto: update  # gelişimde 'update', prod'da migration
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false
  jackson:
    date-format: "yyyy-MM-dd'T'HH:mm:ss"
    time-zone: "Europe/Istanbul"
server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
