spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/todo_db
    username: todo_user
    password: secret
  jpa:
    hibernate:
      ddl-auto: update   # gelişimde 'update', prod'da migration önerilir
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
server:
  port: 8080
